project_id = "tzmhgfjmddkfyffkkmto"

[functions.ai-database-query]
verify_jwt = false

[functions.asignar-propiedad]
verify_jwt = false

[functions.check-property-sold-status]
verify_jwt = false

[functions.generar-draft-proyecto-escritura]
verify_jwt = false

[functions.create-user]
verify_jwt = false
