-- Create table for role-based availability status permissions
CREATE TABLE public.roles_estatus_disponibilidad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol INTEGER NOT NULL REFERENCES roles(id),
  id_estatus_disponibilidad INTEGER NOT NULL REFERENCES estatus_disponibilidad(id),
  activo BOOLEAN NOT NULL DEFAULT true,
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
  fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(id_rol, id_estatus_disponibilidad)
);

-- Enable RLS
ALTER TABLE public.roles_estatus_disponibilidad ENABLE ROW LEVEL SECURITY;

-- Policy for authenticated users to read
CREATE POLICY "Authenticated users can read roles_estatus_disponibilidad"
  ON public.roles_estatus_disponibilidad
  FOR SELECT
  TO authenticated
  USING (true);

-- Policy for admins to manage
CREATE POLICY "Admins can manage roles_estatus_disponibilidad"
  ON public.roles_estatus_disponibilidad
  FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

-- Insert default data: all roles (except Super Admin id=1) can see all active statuses
INSERT INTO public.roles_estatus_disponibilidad (id_rol, id_estatus_disponibilidad)
SELECT r.id, ed.id
FROM roles r
CROSS JOIN estatus_disponibilidad ed
WHERE r.id != 1
  AND r.activo = true
  AND ed.activo = true;